### ISSUE TITLE
Migration to version 12.0

### ISSUE THREAD

**Issue by jarroyomorales** [tegin/cb-addons#132]
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0

Modules to Migrate
----------------------

- [x] account_cash_invoice_inter_company #210
- [x] account_journal_inter_company #167 
- [x] cb_departments_chart #135
- [x] ~~cb_hash_search_purchase~~
- [ ] cb_holidays_compute_mix
- [x] cb_holidays_minimum_days #133 
- [ ] cb_hr_views
- [x] ~~cb_invoice_print_label~~
- [x] cb_invoice_views #145 
- [x] cb_l10n_es_aeat_mod303 #183 
- [x] cb_medical_administration_center #139 
- [x] cb_medical_administration_flag #153 
- [x] cb_medical_administration_healthcare_service #159 
- [x] cb_medical_administration_practitioner_specialty #152 
- [x] cb_medical_administration_reception #165
- [x] cb_medical_authorization #188 
- [x] cb_medical_block_request #212 
- [x] cb_medical_cancel #213 
- [x] cb_medical_careplan_sale #190 
- [x] cb_medical_clinical_laboratory #215
- [x] cb_medical_commission #203 
- [x] cb_medical_coverage_magnetic_str #163 
- [x] cb_medical_financial_coverage_agreement #164 
- [x] cb_medical_financial_coverage_request	#179
- [ ] cb_medical_guard #208
- [x] cb_medical_identifier #175 
- [x] cb_medical_invoice #217
- [x] cb_medical_medication #214 
- [x] cb_medical_pos #211 
- [x] cb_medical_quote #192 
- [x] cb_medical_sale_discount #193 
- [x] cb_medical_sale_invoice #201
- [x] cb_medical_sale_invoice_group_method #202 
- [x] cb_medical_state_update #200 
- [x] cb_medical_views #199 
- [x] cb_medical_workflow_activity #144 
- [x] cb_medical_workflow_plandefinition #176 
- [x] cb_medical_workflow_trigger #177 
- [x] ~~cb_rest_time~~
- [x] cb_sale_report_invoice #166 
- [x] cb_stock_location_warning #149 
- [x] cb_test #204 
- [x] cb_test_constrains #218
- [ ] cb_test_document #218
- [ ] cb_test_invoicing #218
- [X] cb_test_laboratory #218
- [x] cb_test_payment #218
- [x] cb_test_practitioner #218
- [ ] cb_test_sale #218
- [x] cb_test_third_party #218
- [x] cb_test_trigger #218
- [x] cb_test_validation #218
- [x] cb_track_action_picking #184 
- [x] ~~hash_search_account_banking_mandate~~
- [x] ~~hash_search_account_invoice~~
- [x] ~~hash_search_document_scanner~~
- [x] ~~hash_search_document_scanner_queue~~
- [x] ~~hash_search_document_scanner_queue_ssh~~
- [x] ~~hash_search_purchase~~
- [x] ~~hash_search_remote_printer~~
- [x] hr_contract_state #185 
- [x] invoice_hide_refund_description #143 
- [x] invoice_integration_email #231 
- [x] invoice_integration_email_encrypted #231 
- [x] ~~l10n_es_facturae_fields~~
- [ ] l10n_es_facturae_sftp
- [ ] l10n_es_iva_soportado_no_deducible
- [x] medical_administration_firstname #155 
- [x] medical_administration_flag #140
- [x] medical_administration_healthcare_service #159 
- [x] medical_administration_second_lastname #162 
- [x] medical_clinical_laboratory #156 
- [x] medical_document ~~#171~~ #173 
- [x] medical_document_zpl2 #182 
- [x] medical_terminology_icd10pcs #154 
- [x] partner_bank_archive #136
- [x] pos_change_journal #174 
- [x] pos_close_approval #160 
- [x] pos_manual_order #161
- [x] pos_multiple_sessions #158 
- [x] pos_safe_box #194
- [x] pos_validation #216
- [x] product_comercial #150 
- [x] product_nomenclature #151 
- [ ] purchase_invoice_at #142
- [x] ~~purchase_partner_filter~~
- [x] purchase_third_party #178 
- [x] remote_report_to_printer_label #170 
- [x] safe_box #137 
- [x] sale_commission_cancel #148 
- [x] sale_third_party #180 
- [x] sequence_parser #172 
- [x] sequence_safe #147 
- [x] ~~setup~~
- [x] ~~speeder_account~~
- [x] stock_request_template #168 
- [x] stock_putaway_menu #233 
- [x] web_flagbox #157 
- [x] web_icon_widget #141
- [ ] web_session_management #181 
- [x] web_single_app_logo #169
